/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ComplaintTrackerSystem;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

/**
 *
 * @author akino
 */
public class Register extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());

    public Register() {
        initComponents();
        addPlaceholderStyle(JTname, "Enter your full name...");
        addPlaceholderStyle(JTemail, "Enter your student email...");
        addPlaceholderStyle(JTpassword, "Enter your passwords...");
        addPlaceholderStyle(JTconfirmpassword, "Enter your passwords again...");
    }
    
    private void addPlaceholderStyle(javax.swing.JTextField textField, String placeholder) {
        textField.setText(placeholder);
        textField.setForeground(new Color(153, 153, 153));

        textField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (textField.getText().isEmpty()) {
                    textField.setText(placeholder);
                    textField.setForeground(new Color(153, 153, 153));
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainPanel = new javax.swing.JPanel();
        jRegister = new javax.swing.JLabel();
        jName = new javax.swing.JLabel();
        JTname = new javax.swing.JTextField();
        jEmail = new javax.swing.JLabel();
        JTemail = new javax.swing.JTextField();
        jPassword = new javax.swing.JLabel();
        JTpassword = new javax.swing.JTextField();
        jConfirmPassword = new javax.swing.JLabel();
        JTconfirmpassword = new javax.swing.JTextField();
        jbRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(662, 780));
        setResizable(false);

        jMainPanel.setBackground(new java.awt.Color(255, 255, 255));

        jRegister.setBackground(new java.awt.Color(0, 0, 0));
        jRegister.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jRegister.setForeground(new java.awt.Color(0, 0, 0));
        jRegister.setText("Register");

        jName.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jName.setForeground(new java.awt.Color(0, 0, 0));
        jName.setText("Name");

        JTname.setBackground(new java.awt.Color(255, 255, 255));
        JTname.setForeground(new java.awt.Color(0, 0, 0));
        JTname.setText("Enter your full name...");
        JTname.addActionListener(this::JTnameActionPerformed);

        jEmail.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jEmail.setForeground(new java.awt.Color(0, 0, 0));
        jEmail.setText("Email");

        JTemail.setBackground(new java.awt.Color(255, 255, 255));
        JTemail.setForeground(new java.awt.Color(0, 0, 0));
        JTemail.setText("Enter your student email...");

        jPassword.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jPassword.setForeground(new java.awt.Color(0, 0, 0));
        jPassword.setText("Password");

        JTpassword.setBackground(new java.awt.Color(255, 255, 255));
        JTpassword.setForeground(new java.awt.Color(0, 0, 0));
        JTpassword.setText("Enter your password...");

        jConfirmPassword.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jConfirmPassword.setForeground(new java.awt.Color(0, 0, 0));
        jConfirmPassword.setText("Confirm Password");

        JTconfirmpassword.setBackground(new java.awt.Color(255, 255, 255));
        JTconfirmpassword.setForeground(new java.awt.Color(0, 0, 0));
        JTconfirmpassword.setText("Enter your password again...");

        jbRegister.setBackground(new java.awt.Color(66, 103, 238));
        jbRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbRegister.setForeground(new java.awt.Color(255, 255, 255));
        jbRegister.setText("Register");
        jbRegister.addActionListener(this::jbRegisterActionPerformed);

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMainPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTname)
                            .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTemail, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                            .addComponent(JTpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                            .addComponent(JTconfirmpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                            .addComponent(jConfirmPassword)
                            .addComponent(jPassword)
                            .addComponent(jbRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jMainPanelLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jRegister)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jRegister)
                .addGap(18, 18, 18)
                .addComponent(jName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTname, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTemail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jConfirmPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTconfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jbRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRegisterActionPerformed

    private void JTnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTconfirmpassword;
    private javax.swing.JTextField JTemail;
    private javax.swing.JTextField JTname;
    private javax.swing.JTextField JTpassword;
    private javax.swing.JLabel jConfirmPassword;
    private javax.swing.JLabel jEmail;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JLabel jName;
    private javax.swing.JLabel jPassword;
    private javax.swing.JLabel jRegister;
    private javax.swing.JButton jbRegister;
    // End of variables declaration//GEN-END:variables
}
